<a href="https://colab.research.google.com/github/finzawork-dev/ML_Algorithms/blob/main/FeatureEngineering(class3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [18]:
df = pd.read_csv("/content/Udemy_Top5k_New.csv")
df

,reviews_avg,reviews_count,course_duration,lectures_count,level,price_after_discount,main_price,bestseller,students_count
0,4.6,440383,22.0,155,All Levels,319.99,1399.99,0,1629692
1,4.7,248508,64.0,615,All Levels,269.99,1399.99,0,830559
2,4.7,234837,65.5,490,All Levels,349.99,1699.99,1,794897
3,4.6,174576,34.5,472,All Levels,319.99,1599.99,1,634196
4,4.5,171838,80.5,401,All Levels,349.99,849.99,1,727934
...,...,...,...,...,...,...,...,...,...
4787,4.0,129,9.0,86,All Levels,229.99,719.99,0,7269
4788,4.1,129,5.0,96,All Levels,269.99,1399.99,0,776
4789,4.3,129,9.0,92,Beginner,269.99,1299.99,0,787
4790,4.4,129,5.0,31,Intermediate,269.99,849.99,0,1669
4791,4.4,129,5.0,31,Intermediate,269.99,849.99,0,1669

One hot encoding

In [19]:
#get_dummies function Take non numeric feature and convert numeric
X = pd.get_dummies(X)
X

,reviews_count,course_duration,lectures_count,price_after_discount,main_price,bestseller,students_count,level_All Levels,level_Beginner,level_Expert,level_Intermediate
0,440383,22.0,155,319.99,1399.99,0,1629692,True,False,False,False
1,248508,64.0,615,269.99,1399.99,0,830559,True,False,False,False
2,234837,65.5,490,349.99,1699.99,1,794897,True,False,False,False
3,174576,34.5,472,319.99,1599.99,1,634196,True,False,False,False
4,171838,80.5,401,349.99,849.99,1,727934,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
4787,129,9.0,86,229.99,719.99,0,7269,True,False,False,False
4788,129,5.0,96,269.99,1399.99,0,776,True,False,False,False
4789,129,9.0,92,269.99,1299.99,0,787,False,True,False,False
4790,129,5.0,31,269.99,849.99,0,1669,False,False,False,True
4791,129,5.0,31,269.99,849.99,0,1669,False,False,False,True

In [20]:
df.info()
#Total are 4792 but if you see course_duration, it shows less values so you need to clean the data and removenull values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4792 entries, 0 to 4791
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviews_avg           4792 non-null   float64
 1   reviews_count         4792 non-null   int64
 2   course_duration       4658 non-null   float64
 3   lectures_count        4792 non-null   int64
 4   level                 4792 non-null   object
 5   price_after_discount  4792 non-null   float64
 6   main_price            4792 non-null   float64
 7   bestseller            4792 non-null   int64
 8   students_count        4792 non-null   int64
dtypes: float64(4), int64(4), object(1)
memory usage: 337.1+ KB

In [21]:
df = df.dropna()
df
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4658 entries, 0 to 4791
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviews_avg           4658 non-null   float64
 1   reviews_count         4658 non-null   int64
 2   course_duration       4658 non-null   float64
 3   lectures_count        4658 non-null   int64
 4   level                 4658 non-null   object
 5   price_after_discount  4658 non-null   float64
 6   main_price            4658 non-null   float64
 7   bestseller            4658 non-null   int64
 8   students_count        4658 non-null   int64
dtypes: float64(4), int64(4), object(1)
memory usage: 363.9+ KB

In [25]:
X = df.drop('reviews_avg', axis=1)
y = df['reviews_avg']

In [26]:
train_rmse=[]
test_rmse=[]

In [27]:
for d in range(1,6):
  model = PolynomialFeatures(degree = d)
  Extended_X = model.fit_transform(X)

  X_train, X_test, y_train, y_test = train_test_split(Extended_X, y, test_size=0.33, random_state=42)
  model = LinearRegression()
  model.fit(X_train, y_train)

  train_pred = model.predict(X_train)
  test_pred = model.predict(X_test)

  train_rmse.append(np.sqrt(mean_squared_error(y_train, train_pred)))
  test_rmse.append(np.sqrt(mean_squared_error(y_test, test_pred)))

ValueError: could not convert string to float: 'All Levels'